name: 'Draft Release v1.0.0'

on:
  push:
    tags:
      - 'v*'

jobs:
  linux-windows:
    uses: ./.github/workflows/build_lin.yml
    with:
      TAG: ${{ github.ref_name }}
  macos:
    uses: ./.github/workflows/build_mac.yml
    with:
      TAG: ${{ github.ref_name }}
  release:
    name: Create release draft
    needs: [linux-windows, macos]
    runs-on: ubuntu-latest
    outputs:
      changelog-section: ${{ steps.extract.outputs.changelog_section }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Extract section from changelog
        id: extract
        env:
          CHANGELOG_FILE: "CHANGELOG.md"
        run: |
          if [[ ! -f "$CHANGELOG_FILE" ]]; then
            echo "Error: File '$CHANGELOG_FILE' not found!"
            exit 1
          fi
          changelog_section=$(awk '
          /^## / { h2_count++ } 
          h2_count == 2 && !/^## / && !/^$/ { in_section = 1 } 
          h2_count == 3 { in_section = 0 } 
          in_section { 
              if (/^[[:space:]]*$/) { 
                  empty_buffer = empty_buffer $0 "\n" 
              } else { 
                  printf "%s", empty_buffer 
                  empty_buffer = "" 
                  print 
              } 
          }
          ' "$CHANGELOG_FILE")
          echo "changelog_section<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog_section" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          # draft: true
          body: |
            ${{ steps.extract.outputs.changelog_section }}
          files: |
            dist/refractor_linux_x86_64.tgz
            dist/refractor_linux_arm64.tgz
            dist/refractor_macos.tar.gz
            dist/refractor_windows_amd64.zip
            dist/refractor_windows_arm64.zip